### ISSUE TITLE
todo: recipes

### ISSUE THREAD

**Issue by jonschlinkert** [enquirer/enquirer#33]
- [ ] Multilingual support - show how easy it is to add support for multiple languages.
- [ ] spinners and loading indicators
- [ ] asynchronously loaded choices
- [ ] chained prompts
- [ ] using prompts as choices 

What other examples would you like to See?

**Comment by aslafy-z** [comment]
I'd love to have a multi-select editable. This way I could select X tags from a list, and even add choices with some key (`+` for example) and automatically select it after all.

**Comment by jonschlinkert** [comment]
Hi @aslafy-z, I think your request is the same as https://github.com/enquirer/enquirer/issues/30.

**Comment by aslafy-z** [comment]
Thank you for pointing me to the right issue. I must have looked better. It looks great!

**Comment by sqren** [comment]
I'm interested in seeing examples for showing loading indicators upon (async) validation, and how to handle exceptions. 

Case in point: I've made a simple prompt that waits for the user to perform an action (in this case solving a merge conflict), and then pressing submitting. If the merge conflicts were solved the prompt will end successfully, if not it'll require the user to try again. If an exception is thrown by the validation the prompt should end and the exception be re-thrown.

Is the following `EnterPrompt` the correct way to approach this problem?

```js
const { Prompt } = require("enquirer");

class EnterPrompt extends Prompt {
  constructor({ body, customValidation, ...options }) {
    super(options);
    this.body = body;
    this.customValidation = customValidation;
    this.cursorHide();
  }

  async validate() {
    // no validation
    if (!this.customValidation) {
      return true;
    }

    if (this.inProgressPromise) {
      return this.inProgressPromise;
    }

    this.render();
    this.inProgressPromise = this.customValidation();
    const value = await this.inProgressPromise;
    this.inProgressPromise = null;
    return value;
  }

  async render() {
    let { size } = this.state;

    let prefix = await this.prefix();
    let message = await this.message();

    this.clear(size);

    // waiting for the user to submit
    if (!this.state.submitted) {
      this.write(
        `${prefix} ${message}\n${this.body}\n\nPress enter to continue`
      );

    // submitted
    } else {
      // pending
      if (this.state.validating) {
        this.write(
          `${prefix} ${message}\n${this.body}\n\nValidating...`
        );

      // success
      } else {
        this.write(`${prefix} ${message}`);
      }
    }
    this.restore();
  }
}
```

`EnterPrompt` can then be consumed like (with mock data): 

```js

async function init() {
  let i = 0;
  await new EnterPrompt({
    async customValidation() {
      i++;
      return new Promise((resolve) => {
        setTimeout(() => {
          if (i > 2) {
            resolve(true);
          } else {
            this.body =
              "The following files have conflicts and must be fixed:\n - /Users/sqren/srv/enquirer-demo/package.json";
            resolve(false);
          }
        }, 1000);
      });
    },
    message: "Resolve conflicts",
    body:
      "The following files have conflicts and must be fixed:\n - /Users/sqren/srv/enquirer-demo/index.js\n - /Users/sqren/srv/enquirer-demo/package.json",
  }).run();

  console.log("all conflicts resolved!");
}

init().catch((e) => {});
```
